# Build & publish docker images
name: Dockerhub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          platforms: linux/amd64
          build-args: |
            VERSION_TAG=${{ github.ref_name }}
